[package]
name = "r_ebpf_firewall-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
r_ebpf_firewall-common = { path = "../r_ebpf_firewall-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }
xtask = { path = "../xtask" }

[[bin]]
name = "r_ebpf_firewall"
path = "src/main.rs"
