[package]
name = "g_firewall-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
g_firewall-common = { path = "../g_firewall-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }
xtask = { path = "../xtask" }

[[bin]]
name = "g_firewall"
path = "src/main.rs"
